# Generated by Django 5.0.1 on 2024-01-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000000)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=1000)),
                ('youtube', models.CharField(max_length=1000)),
            ],
        ),
    ]
